-- MySQL Script generated by MySQL Workbench
-- Tue Nov 28 08:12:49 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_cs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_cs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_cs` DEFAULT CHARACTER SET utf8mb4 ;
USE `db_cs` ;

-- -----------------------------------------------------
-- Table `db_cs`.`artista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cs`.`artista` (
  `COD_ARTISTA` INT(11) NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(100) NULL DEFAULT NULL,
  `SOBRENOME` VARCHAR(50) NULL DEFAULT NULL,
  `USUARIO` VARCHAR(100) NULL DEFAULT NULL,
  `NASCIMENTO` DATE NULL DEFAULT NULL,
  `EMAIL` VARCHAR(50) NULL DEFAULT NULL,
  `SENHA` VARCHAR(100) NULL DEFAULT NULL,
  `GENERO` VARCHAR(20) NULL DEFAULT NULL,
  `PRONOMES` VARCHAR(20) NULL DEFAULT NULL,
  `ESTADO` VARCHAR(100) NULL DEFAULT NULL,
  `CIDADE` VARCHAR(100) NULL DEFAULT NULL,
  `BAIRRO` VARCHAR(100) NULL DEFAULT NULL,
  `TIPOARTE` VARCHAR(100) NULL DEFAULT NULL,
  `INSTAGRAM` VARCHAR(100) NULL DEFAULT NULL,
  `FACEBOOK` VARCHAR(100) NULL DEFAULT NULL,
  `PINTEREST` VARCHAR(100) NULL DEFAULT NULL,
  `TIK_TOK` VARCHAR(100) NULL DEFAULT NULL,
  `X` VARCHAR(100) NULL DEFAULT NULL,
  `YOUTUBE` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`COD_ARTISTA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `db_cs`.`tipo_arte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cs`.`tipo_arte` (
  `COD_ARTE` INT(11) NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`COD_ARTE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `db_cs`.`tipo_arte_artista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cs`.`tipo_arte_artista` (
  `COD_ARTE` INT(11) NOT NULL AUTO_INCREMENT,
  `COD_ARTISTA` INT(11) NULL DEFAULT NULL,
  `NOME` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`COD_ARTE`),
  INDEX `FK01_ARTISTA` (`COD_ARTISTA` ASC) VISIBLE,
  CONSTRAINT `FK01_ARTISTA`
    FOREIGN KEY (`COD_ARTISTA`)
    REFERENCES `db_cs`.`artista` (`COD_ARTISTA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
